plugins {
	id 'fabric-loom' version "${fabric_b173_loom_version}"
	id 'babric-loom-extension' version "${babric_loom_extension_version}"
	id 'maven-publish'
}

version = project.fabric_b173_mod_version
group = rootProject.maven_group

base {
	archivesName = "${rootProject.archives_base_name}-fabric-b1.7.3"
}

repositories {
	maven { url = "https://maven.glass-launcher.net/babric" }
	maven { url = "https://maven.glass-launcher.net/releases" }
	maven { url = "https://maven.glass-launcher.net/snapshots" }
	maven { url = "https://maven.minecraftforge.net/" }
	maven { url = "https://jitpack.io" }
	mavenCentral()
	exclusiveContent {
		forRepository {
			maven { url = "https://api.modrinth.com/maven" }
		}
		filter { includeGroup("maven.modrinth") }
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.fabric_b173_minecraft_version}"
	mappings "net.glasslauncher:biny:${project.fabric_b173_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.fabric_b173_loader_version}"
	modImplementation("net.modificationstation:StationAPI:${project.fabric_b173_stationapi_version}") {
		exclude group: "babric", module: "fabric-loader"
	}
	implementation "org.slf4j:slf4j-api:${project.fabric_b173_slf4j_version}"
	implementation "org.apache.logging.log4j:log4j-slf4j2-impl:${project.fabric_b173_log4j_version}"
	implementation "org.apache.logging.log4j:log4j-core:${project.fabric_b173_log4j_version}"

	implementation project(":common")
	include implementation("org.joml:joml:1.10.8")
}

configurations.all {
	exclude group: "babric", module: "fabric-loader"
}

remapJar {
	archiveFileName.set("${rootProject.archives_base_name}-v${project.version}+mc${project.fabric_b173_minecraft_version}.jar")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
	it.options.encoding = "UTF-8"
	it.options.compilerArgs.add("-XDignore.symbol.file")
}

java {
	withSourcesJar()
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	dependsOn(":common:classes")
	inputs.property "archivesName", project.base.archivesName

	from(project(":common").sourceSets.main.output)
	from(rootProject.file("LICENSE")) {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.base.archivesName.get()
			from components.java
		}
	}
}
