# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

loom_version=1.16.2
loom_262_version=1.17.17
fabric_b173_loom_version=1.16.3
babric_loom_extension_version=1.17.2

# Mod Properties
mod_version=1.0.1
maven_group=me.onethecrazy
archives_base_name=fbx-player-models-lite

# Fabric 1.21.1 target
fabric_1211_minecraft_version=1.21.1
fabric_1211_yarn_mappings=1.21.1+build.3
fabric_1211_loader_version=0.16.14
fabric_1211_fabric_api_version=0.116.6+1.21.1
fabric_1211_mod_version=2.0.0+1.21.1

# Fabric 26.2 target
fabric_262_minecraft_version=26.2
fabric_262_loader_version=0.19.3
fabric_262_fabric_api_version=0.156.0+26.2
fabric_262_modmenu_version=20.0.1
fabric_262_mod_version=2.0.0+26.2

# Fabric / StationAPI Beta 1.7.3 target
fabric_b173_minecraft_version=b1.7.3
fabric_b173_mappings=b1.7.3+e1fe071
fabric_b173_loader_version=0.19.3
fabric_b173_stationapi_version=2.0.0-alpha.6.4
fabric_b173_slf4j_version=2.0.9
fabric_b173_log4j_version=2.25.2
fabric_b173_mod_version=2.0.0+b1.7.3
