name: nightly-lite

on:
  push:
    branches:
      - clientside

  workflow_dispatch:

permissions:
  contents: write

jobs:
  nightly-lite:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: clientside
            tag: nightly-lite-26.2
            release_name: nightly-lite Build 26.2
            artifact_name: all-the-models-26.2
            artifact_path: "fabric-26.2/build/libs"
            gradlew_build: "./gradlew :fabric-26.2:build"
            release_file: "fbx-player-models-v2.0.0+26.2+mc26.2.jar"
            java_version: "25"
            minecraft_version: "26.2"
            mod_launcher: "fabric"

          - branch: clientside
            tag: nightly-lite-1.21.1
            release_name: nightly-lite Build 1.21.1
            artifact_name: all-the-models-1.21.1
            artifact_path: "fabric-1.21.1/build/libs"
            gradlew_build: "./gradlew :fabric-1.21.1:build"
            release_file: "fbx-player-models-v2.0.0+1.21.1+mc1.21.1.jar"
            java_version: "21"
            minecraft_version: "1.21.1"
            mod_launcher: "fabric"

    steps:
      - name: Get current date
        id: date_step
        run: echo "date=$(date -u +'%y-%m-%d-%H-%m')" >> $GITHUB_OUTPUT
        
      - name: checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: setup jdkname: nightly

on:
  push:
    branches:
      - clientside

  workflow_dispatch:

permissions:
  contents: write

jobs:
  nightly:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: clientside
            tag: nightly-26.2
            release_name: Nightly Build 26.2
            artifact_name: all-the-models-26.2
            artifact_path: "fabric-26.2/build/libs"
            gradlew_build: "./gradlew :fabric-26.2:build"
            release_file: "fbx-player-models-v2.0.0+26.2+mc26.2.jar"
            java_version: "25"
            minecraft_version: "26.2"
            mod_launcher: "fabric"

          - branch: clientside
            tag: nightly-1.21.1
            release_name: Nightly Build 1.21.1
            artifact_name: all-the-models-1.21.1
            artifact_path: "fabric-1.21.1/build/libs"
            gradlew_build: "./gradlew :fabric-1.21.1:build"
            release_file: "fbx-player-models-v2.0.0+1.21.1+mc1.21.1.jar"
            java_version: "21"
            minecraft_version: "1.21.1"
            mod_launcher: "fabric"

    steps:
      - name: Get current date
        id: date_step
        run: echo "date=$(date -u +'%y-%m-%d-%H-%m')" >> $GITHUB_OUTPUT
        
      - name: checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java_version }}
          distribution: "microsoft"

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ${{ matrix.gradlew_build }}

      - name: capture build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}

      - name: prepare release tag
        env:
          TAG_NAME: ${{ matrix.tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag -f "$TAG_NAME"
          git push --force origin "refs/tags/$TAG_NAME"

          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

      - name: delete old release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ matrix.tag }}
        run: |
          gh release delete "$TAG_NAME" --yes || true

      - name: create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ matrix.tag }}
          RELEASE_NAME: ${{ matrix.release_name }}
          BRANCH_NAME: ${{ matrix.branch }}
          BUILD_PATH: ${{ matrix.artifact_path }}
        run: |
          gh release create "$TAG_NAME" $BUILD_PATH/* \
            --title "$RELEASE_NAME" \
            --notes "Automatic nightly build.

          Branch: $BRANCH_NAME
          Commit: $COMMIT_SHA" \
            --prerelease \
            --verify-tag

      - name: set clear version for modrinth
        run: cp ${{ matrix.artifact_path }}/${{ matrix.release_file }} ${{ matrix.artifact_path }}/fbx-player-models-nightly-${{ matrix.minecraft_version }}-${{ steps.date_step.outputs.date }}.jar

      - name: create modrinth release
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ vars.MODRINTH_ID }}
          channel: "alpha"
          changelog: "Automatic nightly build from [GitHub repo](https://github.com/aksulightning/FBXPlayerModels)."
          version: ${{ matrix.branch }}-nightly-${{ steps.date_step.outputs.date }}
          loaders: ${{ matrix.mod_launcher }}
          game-versions: ${{ matrix.minecraft_version }}
          files: ${{ matrix.artifact_path }}/fbx-player-models-nightly-${{ matrix.minecraft_version }}-${{ steps.date_step.outputs.date }}.jar
            

        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java_version }}
          distribution: "microsoft"

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ${{ matrix.gradlew_build }}

      - name: capture build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}

      - name: prepare release tag
        env:
          TAG_NAME: ${{ matrix.tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag -f "$TAG_NAME"
          git push --force origin "refs/tags/$TAG_NAME"

          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

      - name: delete old release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ matrix.tag }}
        run: |
          gh release delete "$TAG_NAME" --yes || true

      - name: create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ matrix.tag }}
          RELEASE_NAME: ${{ matrix.release_name }}
          BRANCH_NAME: ${{ matrix.branch }}
          BUILD_PATH: ${{ matrix.artifact_path }}
        run: |
          gh release create "$TAG_NAME" $BUILD_PATH/* \
            --title "$RELEASE_NAME" \
            --notes "Automatic nightly-lite build.

          Branch: $BRANCH_NAME
          Commit: $COMMIT_SHA" \
            --prerelease \
            --verify-tag
            
